### ISSUE TITLE
string parsing error when registering user id

### ISSUE THREAD

**Issue by brain-murphy** [djtech42/YikYakTerminal#12]
for some reason, there is an issue parsing a float location to a string. I have already fixed this myself, but the simplicity of the error made me wonder if I am working with the latest version. Here is the error:

```
C:\Users\Brian\Code\YikYakTerminal>python3 YikYak.py

Yik Yak Command Line Edition : Created by djtech42


Enter college name or address: Georgia Tech

Traceback (most recent call last):
  File "YikYak.py", line 45, in main
    f = open("userID", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'userID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "YikYak.py", line 470, in <module>
    main()
  File "YikYak.py", line 54, in main
    remoteyakker = pk.Yakker(None, coordlocation, True)
  File "C:\Users\Brian\Code\YikYakTerminal\API.py", line 199, in __init__
    self.register_id_new(user_id)
  File "C:\Users\Brian\Code\YikYakTerminal\API.py", line 219, in register_id_new

    result = self.get("registerUser", params)
  File "C:\Users\Brian\Code\YikYakTerminal\API.py", line 278, in get
    "Cookie": "lat=" + self.location.latitude + "; long=" + self.location.longit
ude + "; pending=deleted; expires=Thu,01-Jan-1970 00:00:01 GMT;Max-Age=0",
TypeError: Can't convert 'float' object to str implicitly
```

**Comment by djtech42** [comment]
Please refer to https://github.com/djtech42/YikYakTerminal/issues/11 for further discussion of registering new users.
